# Default server
# TODO (jwj):
# * Clarify server_name
# * Clarify stub_status

server {
    listen 80;
    server_name _;

    location / {
        add_header Content-Type application/json;
        return 200 '{"message": "Hello from Nginx!", "host": "$host", "remote_addr": "$remote_addr", "proxy_add_x_forwarded_for": "$proxy_add_x_forwarded_for", "http_x_forwarded_for": "$http_x_forwarded_for"}';
    }

    location /gte-qwen2-15b/ {
        proxy_pass http://emb0/;
    }

    location /ds-r1-32b-awq/ {
        proxy_pass http://gen0/;
    }

    location /qwen25-v1-72b-awq/ {
        proxy_pass http://gen1/;
    }

    location /qwen-qwq-32b-awq/ {
        proxy_pass http://gen2/;
    }

    location /nvitop-exporter/ {
        proxy_pass http://nvitop-exporter/;
    }

    # NginX status page
    location /nginx_status {
        stub_status;
        # Observability within the container only
        allow 127.0.0.1;
        deny all;
    }
}