# Upstreams
# TODO (jwj): 
# * Separate the model serving and observability
# * Study the logic of max_fails and fail_timeout
#     * Read https://blog.csdn.net/u014686399/article/details/138221013

upstream emb0 {
    server sgl_gte-qwen2-1.5b:30001; # max_fails=3 fail_timeout=30s;
}

upstream gen0 {
    server sgl_ds-r1-32b-awq:30002;
}

upstream gen1 {
    server sgl_qwen2.5-vl-72b-awq:30003;
}

upstream gen2 {
    server sgl_qwen-qwq-32b-awq:30000;
}

upstream nvitop-exporter {
    server nvitop-exporter:5050;
}